config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: { sessions: 'admins/sessions' }
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home"

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :users, shallow: true do  #user has many events and has one org role
        resources :events, shallow: true
        resources :organization_roles, shallow: true
      end
      resources :organizations, shallow: true do  #orgs has many events and has many org roles
        resources :events, :organization_roles, shallow: true
      end
      resources :users, shallow: true do  #user has many invitations, which are linked to comments and votes
        resources :invitations, shallow: true do
          resources :comments, :votes, shallow: true
        end
      end
      resources :events, shallow: true do  #event has many invitations, comments and votes
        resources :invitations, :comments, :votes, shallow: true
      end
    end
  end

  resources :users, defaults: { format: :html }, shallow: true do  #user has many events, messages and has one org role
    resources :messages, defaults: { format: :html }, shallow: true
    resources :events, defaults: { format: :html }, shallow: true do
      resources :invitations, :comments, :votes, defaults: { format: :html }, shallow: true
    end
    resources :organization_roles, defaults: { format: :html }, shallow: true
  end
  resources :organizations, defaults: { format: :html }, shallow: true do  #orgs has many events and has many org roles
    resources :events, defaults: { format: :html }, shallow: true do
      resources :invitations, :comments, :votes, defaults: { format: :html }, shallow: true
    end
    resources :organization_roles, defaults: { format: :html }, shallow: true
  end
  resources :users, defaults: { format: :html }, shallow: true do  #user has many invitations, which are linked to comments and votes
    resources :invitations, defaults: { format: :html }, shallow: true do
      resources :comments, :votes, defaults: { format: :html }, shallow: true
    end
  end

  resource :aup_tos, only: [:show]
  match '/search_users', to: "search_users#search_users", via: [:post, :get]
  match '/search_organizations', to: "search_organizations#search_organizations", via: [:post, :get]
  match '/search_events', to: "search_events#search_events", via: [:post, :get]

end

app/models/organization_role.rb
class OrganizationRole < ApplicationRecord
  belongs_to :organization
  belongs_to :user
end

app/controllers/api/v1/organization_roles_controller.rb
class API::V1::OrganizationRolesController < APIController
  before_action :set_organization_role, only: [:show, :edit, :update, :destroy]

  # GET /organization_roles
  # GET /organization_roles.json
  def index
    @organization_roles = OrganizationRole.where(organization_id: params[:organization_id])
  end

  # GET /organization_roles/1
  # GET /organization_roles/1.json
  def show
  end

  # GET /organization_roles/new
  def new
    @organization_role = OrganizationRole.new
  end

  # GET /organization_roles/1/edit
  def edit
  end

  # POST /organization_roles
  # POST /organization_roles.json
  def create
    @organization_role = OrganizationRole.new(organization_role_params)
    @organization_role.user = User.find(params[:user_id])
    @organization_role.organization = Organization.find(params[:organization_id])


    if @organization_role.save
      render :show, status: :created, location: @organization_role
    else
      render json: @organization_role.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /organization_roles/1
  # PATCH/PUT /organization_roles/1.json
  def update
    if @organization_role.update(organization_role_params)
      render :show, status: :ok, location: api_v1_organization_organization_roles_path(@organization_role)
    else
      render json: @organization_role.errors, status: :unprocessable_entity
    end
  end

  # DELETE /organization_roles/1
  # DELETE /organization_roles/1.json
  def destroy
    @organization_role.destroy
    head :no_content
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization_role
      @organization_role = OrganizationRole.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def organization_role_params
      params.fetch(:organization_role, {}).permit(:id, :user_id, :organization_id, :role)
    end
end

app/controllers/organization_roles_controller.rb
class OrganizationRolesController < ApplicationController
  before_action :set_organization_role, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /organization_roles
  # GET /organization_roles.json
  def index
    @organization_roles = OrganizationRole.includes(:user, :organization).where(user_id: params[:user_id])
  end

  # GET /organization_roles/1
  # GET /organization_roles/1.json
  def show
  end

  # GET /organization_roles/new
  def new
    @organization = Organization.find(params[:organization_id])
    @organization_role = OrganizationRole.new
    @organization_role.organization = @organization
    @organization_role.user = current_user
  end

  # GET /organization_roles/1/edit
  def edit
  end

  # POST /organization_roles
  # POST /organization_roles.json
  def create
    @organization = Organization.find(params[:organization_id])
    @organization_role = OrganizationRole.new(organization_role_params)
    @organization_role.organization = @organization
    @organization_role.user = current_user

    respond_to do |format|
      if @organization_role.save
        format.html { redirect_to @organization, notice: 'You have succesfully joined the organization.' }
        format.json { render :show, status: :created, location: @organization_role }
      else
        format.html { render :new }
        format.json { render json: @organization_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organization_roles/1
  # PATCH/PUT /organization_roles/1.json
  def update
    respond_to do |format|
      if @organization_role.update(organization_role_params)
        format.html { redirect_to @organization_role, notice: 'Organization role was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization_role }
      else
        format.html { render :edit }
        format.json { render json: @organization_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organization_roles/1
  # DELETE /organization_roles/1.json
  def destroy
    @organization_role.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Action was successfully executed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization_role
      @organization_role = OrganizationRole.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def organization_role_params
      params.fetch(:organization_role, {}).permit(:id, :user, :organization, :role, :user_id, :organization_id)
    end
end

app/helpers/organization_roles_helper.rb
module OrganizationRolesHelper
end

app/views/organization_roles/_form.html.erb
<div class="row ml-0 m-3">
  <%= form_with model: [@organization, @organization_role], local: true do |form| %>
    <%= errors_for @organization_role %>
    <div class="form-group">
      <h4><%= form.label :join_organization? %></h4>
    </div>
    <div class="form-group">
      <%= form.hidden_field :role, value: 0 %>
    </div>
    <div class="form-group mt-2">
      <%= form.submit "Yes", class: ["btn", "btn-primary"] %>
      <%= link_to "No", :back, class: ["btn", "btn-secondary"] %>
    </div>
  <% end %>
</div>

app/views/organization_roles/edit.html.erb
<h1>Editing Organization Role</h1>

<%= render 'form', organization_role: @organization_role %>

<%= link_to 'Show', @organization_role %> |
<%= link_to 'Back', organization_roles_path %>

app/views/organization_roles/index.html.erb
<div class="row ml-0 mt-3">
  <h4>My Organization Roles</h4>
</div>
<div class="row ml-0">
  <% if @organization_roles.count == 0 %>
    <div class="row ml-0 mt-3">
      <p>You don't belong to any Organization!</p>
    </div>
  <% else %>
    <div class="row ml-0 mt-3">
      <table class="table">
        <thead>
        <th scope="col">N</th>
        <th scope="col">Organization</th>
        <th scope="col">User</th>
        <th scope="col">Role</th>
        </thead>
        <tbody>
        <% @organization_roles.each_with_index do |organization_role, i| %>
          <tr>
            <td><%= i+1 %></td>
            <td><%= link_to organization_role.organization.name, organization_path(organization_role.organization_id) %></td>
            <td><%= link_to organization_role.user.username, user_path(organization_role.user_id) %></td>
            <td><% if organization_role.role == 0%> Normal <% else %> Moderator <% end %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
</div>

<div class="row ml-0 mt-3">
  <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to 'Back', root_path %></button>
</div>

app/views/organization_roles/new.html.erb
<%= render "form", locals: { organization: @organization, organization_role: @organization_role } %>

app/views/organization_roles/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_organization_role_path(@organization_role) %> |
<%= link_to 'Back', organization_roles_path %>