config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: { sessions: 'admins/sessions' }
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home"

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :users, shallow: true do  #user has many events and has one org role
        resources :events, shallow: true
        resources :organization_roles, shallow: true
      end
      resources :organizations, shallow: true do  #orgs has many events and has many org roles
        resources :events, :organization_roles, shallow: true
      end
      resources :users, shallow: true do  #user has many invitations, which are linked to comments and votes
        resources :invitations, shallow: true do
          resources :comments, :votes, shallow: true
        end
      end
      resources :events, shallow: true do  #event has many invitations, comments and votes
        resources :invitations, :comments, :votes, shallow: true
      end
    end
  end

  resources :users, defaults: { format: :html }, shallow: true do  #user has many events, messages and has one org role
    resources :messages, defaults: { format: :html }, shallow: true
    resources :events, defaults: { format: :html }, shallow: true do
      resources :invitations, :comments, :votes, defaults: { format: :html }, shallow: true
    end
    resources :organization_roles, defaults: { format: :html }, shallow: true
  end
  resources :organizations, defaults: { format: :html }, shallow: true do  #orgs has many events and has many org roles
    resources :events, defaults: { format: :html }, shallow: true do
      resources :invitations, :comments, :votes, defaults: { format: :html }, shallow: true
    end
    resources :organization_roles, defaults: { format: :html }, shallow: true
  end
  resources :users, defaults: { format: :html }, shallow: true do  #user has many invitations, which are linked to comments and votes
    resources :invitations, defaults: { format: :html }, shallow: true do
      resources :comments, :votes, defaults: { format: :html }, shallow: true
    end
  end

  resource :aup_tos, only: [:show]
  match '/search_users', to: "search_users#search_users", via: [:post, :get]
  match '/search_organizations', to: "search_organizations#search_organizations", via: [:post, :get]
  match '/search_events', to: "search_events#search_events", via: [:post, :get]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :events, as: :creator, dependent: :destroy
  has_many :organization_roles, dependent: :destroy
  has_many :organizations, through: :organization_roles

  has_many :invitations, dependent: :destroy
  has_many :messages, dependent: :destroy

  has_one_attached :profile_image

  validates :name, :lastName, :username, :email, presence: true
  validates :username, :email, uniqueness: true
  validates :email, format:
      { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
end

app/controllers/api/v1/users_controller.rb
class API::V1::UsersController < APIController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    if @user.save
      render :show, status: :created, location: @user
    else
      render json: @user.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if @user.update(user_params)
      render :show, status: :ok, location: api_v1_user_path(@user)
    else
      render json: @user.errors, status: :unprocessable_entity
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    head :no_content
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.fetch(:user, {}).permit(:id, :name, :lastName, :username, :email, :mainRole)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.where(id: params[:id])
    x = @user.pluck(:id)[0]
    @invitations = []
    if user_signed_in?
      if @user[0].id == current_user.id
        @invitations = Invitation.includes(:user, :event).where(user_id: x, host: 0)
      else
        @inv = Invitation.includes(:user, :event).where(user_id: x, host: 0)
        for j in @inv
          if j.event.privacy == 0
            @invitations << j
          end
        end
      end
    elsif admin_signed_in?
      @invitations = Invitation.includes(:user, :event).where(user_id: x, host: 0)
    else
      @inv = Invitation.includes(:user, :event).where(user_id: x, host: 0)
      for j in @inv
        if j.event.privacy == 0
          @invitations << j
        end
      end
    end

    orgs = OrganizationRole.where(user_id: x, role: 1).pluck("organization_id")
    if orgs.count > 0
      @events = []
      for i in orgs
        if user_signed_in?
          if @user[0].id == current_user.id
            for j in Event.where(creator_id: i)
              @events << j
            end
          else
            for j in Event.where(creator_id: i, privacy: 0)
              @events << j
            end
          end
        elsif admin_signed_in?
          for j in Event.where(creator_id: i)
            @events << j
          end
        else
          for j in Event.where(creator_id: i, privacy: 0)
            @events << j
          end
        end
      end

      if user_signed_in?
        if @user[0].id == current_user.id
          for y in Event.where(creator_id: x, creator_type: "User")
            @events << y
          end
        else
          for y in Event.where(creator_id: x, creator_type: "User", privacy: 0)
            @events << y
          end
        end
      elsif admin_signed_in?
        for y in Event.where(creator_id: x, creator_type: "User")
          @events << y
        end
      else
        for y in Event.where(creator_id: x, creator_type: "User", privacy: 0)
          @events << y
        end
      end

    else
      if user_signed_in?
        if @user[0].id == current_user.id
          @events = Event.where(creator_id: x, creator_type: "User")
        else
          @events = Event.where(creator_id: x, creator_type: "User", privacy: 0)
        end
      elsif admin_signed_in?
        @events = Event.where(creator_id: x, creator_type: "User")
      else
        @events = Event.where(creator_id: x, creator_type: "User", privacy: 0)
      end
    end

  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if @user.update(user_params)
      if user_signed_in?
        sign_in :user, @user, bypass: true
      end
      flash[:notice] = 'User was successfully updated.'
      redirect_to @user
    else
      redirect_to @user
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @messages = Message.all
    for j in @messages
      if j.receptor == @user.id
        j.destroy
      end
    end

    destroy_user_session_path
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.fetch(:user, {}).permit(:username, :name, :lastName, :biography, :profile_image, :location, :password)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="row ml-0">
  <%= form_with model: @user, local: true do |form| %>
    <%= errors_for @user %>
    <div class="form-group">
      <%= form.label :username %>
      <%= form.text_field :username, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :last_name %>
      <%= form.text_field :lastName, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :biography %>
      <%= form.text_area :biography, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :location %>
      <%= form.text_field :location, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :profile_image %>
      <%= form.file_field :profile_image, class: "form-control-file" %>
    </div>

    <div class="form-group mt-2">
      <%= form.submit submit_btn_text, class: ["btn", "btn-primary"] %>
      <%= link_to "Back", :back, class: ["btn", "btn-secondary"] %>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="row ml-0 mt-3">
  <h2>Edit "<%=@user.username%>'s" Profile</h2>
</div>
<div class="row ml-0 mt-2">
  <p>Please enter the required information to edit "<%=@user.username%>'s'" profile:</p>
</div>
<%= render partial: "form",
           locals: {
               user: @user,
               submit_btn_text: "Update"
           } %>

app/views/users/index.html.erb
<div class="row ml-0 mt-3">
  <h4>Users</h4>
</div>
<form class="form-inline mr-3" id="search_form">
  <input class="form-control mr-sm-2" id="search_box" type="search" placeholder="Search" aria-label="Search">
  <button class="btn btn-outline-success my-2 my-sm-0" id="search_users_button" type="submit">Search</button>
</form>
<div class="row ml-0">
  <div class="row ml-0 mt-3">
    <table class="table">
      <thead>
      <tr>
        <th scope="col">Username</th>
        <th scope="col">Name</th>
        <% if admin_signed_in? %>
          <th scope="col">Actions</th>
        <% end %>
      </tr>
      </thead>
      <tbody>
      <% @users.each_with_index do |user| %>
        <tr>
          <td><%= link_to user.username, user_path(user.id) %></td>
          <td><%= user.name %> <%= user.lastName %></td>
          <% if admin_signed_in? %>
            <td>
              <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to "Edit", edit_user_path(user.id) %></button>
              <button type="button" class="btn btn-sm btn-outline-danger"><%= link_to "Delete", user, method: :delete, data: {confirm: "Are you sure?"}, remote: true %></button>
            </td>
          <% end %>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="row ml-0 mt-3">
  <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to 'Back', root_path %></button>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="row ml-0 mt-3">
  <ul class="list-unstyled">
    <% @user.each_with_index do |user| %>
      <h3><%= user.username %>
        <% if user_signed_in? %>
          <% if user.id == current_user.id %>
            <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to "Edit", edit_user_path(current_user.id) %></button>
            <p class="float-right">
              <button type="button" class="btn btn-sm btn-outline-danger"><%= link_to "Delete", user, method: :delete, data: {confirm: "Are you sure?"}, remote: true %></button>
            </p>
          <% end %>
        <% end %>

        <% if admin_signed_in? %>
          <p class="float-right">
            <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to "Edit", edit_user_path(@user[0].id) %></button>
            <button type="button" class="btn btn-sm btn-outline-danger"><%= link_to "Delete", user, method: :delete, remote: true %></button>
          </p>
        <% end %>
      </h3>
      <% if user.profile_image.attached? == true%>
        <%= image_tag(user.profile_image, width: "250px", background: "#55595c", color: "#eceeef") %>
      <% else %> <%= image_tag(src="http://placehold.it/80", width: "250px", background: "#55595c", color: "#eceeef") %> <% end %>
    <% end %>
  </ul>
</div>
<div class="row ml-0 mt-3">
  <ul class="list-unstyled">
    <% @user.each_with_index do |user| %>
      <li><strong>Name:</strong> <%= user.name %> <%= user.lastName %></li>
      <li><strong>Mail:</strong> <%= user.email %></li>
      <li><strong>Biography:</strong> <%= user.biography %></li>
      <li><strong>Location:</strong> <%= user.location %></li>

      <% if user.lastAccess == nil %>
        <li><strong>Last access: </strong>Never!</li>
      <% else %>
        <% if user_signed_in? %>
          <% if current_user == user %>
            <li><strong>Last access:</strong> Online</li>
          <% else %>
            <li><strong>Last access:</strong> <%= user.lastAccess %></li>
          <% end %>
        <% else %>
          <li><strong>Last access:</strong> <%= user.lastAccess %></li>
        <% end %>
      <% end %>

      <% if user_signed_in? %>
        <% if current_user == user %>
          <li><%= link_to "Change Password", edit_user_registration_path, class: ["btn", "btn-outline-primary"] %></li>
        <% end %>
      <% end %>

    <% end %>
  </ul>
</div>

<div class="row ml-0 mt-3">
  <h5>Invitations</h5>
</div>
<div class="row ml-0">
  <ul class="list-unstyled">
    <% if @invitations.count == 0 %>
      <div class="row ml-0 ">
        No invitations!
      </div>
    <% else %>
      <% @invitations.each_with_index do |invitation| %>
        <li><strong><%= link_to invitation.event.name, event_path(invitation.event.id) %></strong></li>
      <% end %>
    <% end %>
  </ul>
</div>

<div class="row ml-0 mt-3">
  <h5>Created Events</h5>
</div>
<div class="row ml-0">
  <ul class="list-unstyled">
    <% if @events.count == 0 %>
      <div class="row ml-0 ">
        No created events!
      </div>
    <% else %>
      <% @events.each_with_index do |event| %>
        <li><strong><%= link_to event.name, event_path(event.id) %></strong></li>
      <% end %>
    <% end %>
  </ul>
</div>

<div class="row ml-0 mt-3">
  <h5>Organization Roles</h5>
</div>
<div class="row ml-0">
  <% @organization_roles = OrganizationRole.includes(:user, :organization).where(user_id: @user[0].id) %>
  <% if @organization_roles.count == 0 %>
    <div class="row ml-0 mt-3">
      <p><%= @user[0].username %> doesn't belong to any Organization!</p>
    </div>
  <% else %>
    <div class="row ml-0 mt-3">
      <table class="table">
        <thead>
        <th scope="col">Organization</th>
        <th scope="col">Role</th>
        </thead>
        <tbody>
        <% @organization_roles.each_with_index do |organization_role| %>
          <tr>
            <td><%= link_to organization_role.organization.name, organization_path(organization_role.organization_id) %></td>
            <td><% if organization_role.role == 0%> Normal <% else %> Moderator <% end %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
</div>


<br>
<button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to 'Back', :back %></button>