config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: { sessions: 'admins/sessions' }
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home"

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :users, shallow: true do  #user has many events and has one org role
        resources :events, shallow: true
        resources :organization_roles, shallow: true
      end
      resources :organizations, shallow: true do  #orgs has many events and has many org roles
        resources :events, :organization_roles, shallow: true
      end
      resources :users, shallow: true do  #user has many invitations, which are linked to comments and votes
        resources :invitations, shallow: true do
          resources :comments, :votes, shallow: true
        end
      end
      resources :events, shallow: true do  #event has many invitations, comments and votes
        resources :invitations, :comments, :votes, shallow: true
      end
    end
  end

  resources :users, defaults: { format: :html }, shallow: true do  #user has many events, messages and has one org role
    resources :messages, defaults: { format: :html }, shallow: true
    resources :events, defaults: { format: :html }, shallow: true do
      resources :invitations, :comments, :votes, defaults: { format: :html }, shallow: true
    end
    resources :organization_roles, defaults: { format: :html }, shallow: true
  end
  resources :organizations, defaults: { format: :html }, shallow: true do  #orgs has many events and has many org roles
    resources :events, defaults: { format: :html }, shallow: true do
      resources :invitations, :comments, :votes, defaults: { format: :html }, shallow: true
    end
    resources :organization_roles, defaults: { format: :html }, shallow: true
  end
  resources :users, defaults: { format: :html }, shallow: true do  #user has many invitations, which are linked to comments and votes
    resources :invitations, defaults: { format: :html }, shallow: true do
      resources :comments, :votes, defaults: { format: :html }, shallow: true
    end
  end

  resource :aup_tos, only: [:show]
  match '/search_users', to: "search_users#search_users", via: [:post, :get]
  match '/search_organizations', to: "search_organizations#search_organizations", via: [:post, :get]
  match '/search_events', to: "search_events#search_events", via: [:post, :get]

end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, polymorphic: true
  has_many :invitations, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy

  has_one_attached :image

  validates :name, :description, :date, :location, :creation_date, presence: true
  validates :date, not_in_past: true
end

app/controllers/api/v1/events_controller.rb
class API::V1::EventsController < APIController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.where(creator_id: params[:user_id])
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    if @event.save
      render :show, status: :created, location: @event
    else
      render json: @event.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    if @event.update(event_params)
      render :show, status: :ok, location: api_v1_user_events_path(@event)
    else
      render json: @event.errors, status: :unprocessable_entity
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    head :no_content
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.fetch(:event, {}).permit(:id, :creator_id, :creator_type, :name, :date, :privacy, :description)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    x = current_user.id
    @moderator = OrganizationRole.where(user_id: x, role: 1).pluck("organization_id")
    orgs = OrganizationRole.where(user_id: x, role: 1).pluck("organization_id")
    if orgs.count > 0
      @events = []
      for i in orgs
        for j in Event.where(creator_id: i)
          @events << j
        end
      end
      for y in Event.where(creator_id: x, creator_type: "User")
        @events << y
      end
    else
      @events = Event.where(creator_id: x, creator_type: "User")
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.where(id: params[:id])
    @votes_title = Vote.where(event_id: params[:id]).limit(1)
    @votes = Vote.where(event_id: params[:id])
    @guests = Invitation.where(event_id: params[:id])
    @comments = User.select('users.username, users.id, comments.content, comments.id as comment_id').joins(invitations: :comments).where(invitations: { event_id: params[:id] })
  end

  # GET /events/new
  def new
    @event = Event.new

  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)


    respond_to do |format|
      if @event.save

        @new_event_creator = Invitation.new
        @new_event_creator.user = current_user
        @new_event_creator.event = @event
        @new_event_creator.host = 1
        if  @new_event_creator.errors.blank?
          @new_event_creator.save
        end

        format.html { redirect_to user_events_path(current_user.id), notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      if user_signed_in?
        format.html { redirect_to user_events_path(current_user.id), notice: 'Event was successfully deleted.' }
      elsif admin_signed_in?
        format.html { redirect_to root_path, notice: 'Event was successfully deleted.' }
      end
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.fetch(:event, {}).permit(:id, :name, :description, :date, :privacy, :image, :creator_type, :creator_id, :location, :creation_date)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<div class="row ml-0">
  <%= form_with model: @event, local: true do |form| %>
    <%= errors_for @event %>
    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :description %>
      <%= form.text_area :description, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :location %>
      <%= form.text_field :location, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :date %>
      <%= form.text_field :date, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :Make_private %>
      <%= form.check_box :privacy, {}, 1, 0 %>
    </div>
    <div class="form-group">
      <%= form.label :Event_image %>
      <%= form.file_field :image, class: "form-control-file" %>
    </div>
    <div class="form-group mt-2">
      <%= form.submit submit_btn_text, class: ["btn", "btn-primary"] %>
      <% if user_signed_in? %>
        <%= link_to "Back", user_events_path(current_user.id), class: ["btn", "btn-secondary"] %>
      <% else %>
        <%= link_to "Back", root_path, class: ["btn", "btn-secondary"] %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/events/edit.html.erb
<div class="row ml-0 mt-3">
  <h2>Edit "<%=@event.name%>"</h2>
</div>
<div class="row ml-0 mt-2">
  <p>Please enter the required information to edit "<%=@event.name%>":</p>
</div>
<%= render partial: "form",
           locals: {
               event: @event,
               submit_btn_text: "Update"
           } %>

app/views/events/index.html.erb
<div class="row ml-0 mt-3">
  <h4>Created Events</h4>
</div>

<div class="btn-block ml-0 mt-2 mb-3">
  <%= link_to "Create Event as " + @current_user.username, new_user_event_path(@current_user.id), class: ["btn", "btn-primary"] %>
  <% @moderator.each do |moderator| %>
    <%= link_to "Create Event as " + Organization.where(id: moderator).pluck(:name)[0] , new_organization_event_path(moderator), class: ["btn", "btn-primary"] %>
  <% end %>
</div>

<form class="form-inline mr-3" id="search_form">
  <input class="form-control mr-sm-2" id="search_box" type="search" placeholder="Search" aria-label="Search">
  <button class="btn btn-outline-success my-2 my-sm-0" id="search_events_button" type="submit">Search</button>
</form>

<div class="row ml-0 mt-3">
  <% if @events.count == 0 %>
    <div class="row ml-0">
      No created events at the moment!
    </div>
  <% else %>
    <% @events.each do |event| %>
      <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
          <% if event.image.attached? == true%>
            <%= image_tag(event.image, class: "card-img-top", width: "400px", background: "#55595c", color: "#eceeef") %>
          <% else %> <%= image_tag("thumbnail.svg", class: "card-img-top", width: "400px", background: "#55595c", color: "#eceeef") %> <% end %>
          <div class="card-body">
            <p class="card-text"><%= link_to event.name, event %></p>
            <p class="card-text"><%= event.date %></p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to "View", event %></button>
                <% if event.creator_type == "User" %>
                  <% if @current_user.id == event.creator_id %>
                    <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to "Edit", edit_event_path(event.id) %></button>
                    <button type="button" class="btn btn-sm btn-outline-danger"><%= link_to "Delete", event, method: :delete, data: {confirm: "Are you sure?"}, remote: true%></button>
                  <% end %>
                <% elsif event.creator_type == "Organization" %>
                  <% if OrganizationRole.where(user_id: @current_user.id, organization_id: event.creator_id).pluck("role") == [1] %>
                    <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to "Edit", edit_event_path(event.id) %></button>
                    <button type="button" class="btn btn-sm btn-outline-danger"><%= link_to "Delete", event, method: :delete, data: {confirm: "Are you sure?"}, remote: true%></button>
                  <% end %>
                <% end %>
              </div>
              <% if event.date != nil %>
                <small class="text-muted"><%= "#{(event.date.to_date - DateTime.now.to_date).to_i} days left!" %></small>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

<div class="row ml-0 mt-3">
  <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to 'Back', root_path %></button>
</div>

app/views/events/new.html.erb
<div class="row ml-0 mt-3">
  <h2>New Event</h2>
</div>
<div class="row ml-0 mt-2">
  <p>Please enter the required information to create a new event:</p>
</div>

<% url = request.path_info %>
<% if url.include?('user') %>
  <div class="row ml-0">
    <%= form_with model: [current_user, @event], local: true do |form| %>
      <%= errors_for @event %>
      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= form.hidden_field :creator_type, value: "User" %>
        <%= form.hidden_field :creator_id, value: current_user.id %>
        <%= form.hidden_field :creation_date, value: Time.current %>
      </div>
      <div class="form-group">
        <%= form.label :description %>
        <%= form.text_area :description, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= form.label :location %>
        <%= form.text_field :location, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= form.label :date %>
        <%= form.text_field :date, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= form.label :Make_private %>
        <%= form.check_box :privacy, {}, 1, 0 %>
      </div>
      <div class="form-group">
        <%= form.label :Event_image %>
        <%= form.file_field :image, class: "form-control-file" %>
      </div>
      <div class="form-group mt-2">
        <%= form.submit "Create", class: ["btn", "btn-primary"] %>
        <%= link_to "Back", user_events_path(current_user.id), class: ["btn", "btn-secondary"] %>
      </div>
    <% end %>
  </div>
<% else %>
  <% path_segments = url.split("/") %>
  <% @organization = Organization.find(path_segments[2]) %>
  <div class="row ml-0">
    <%= form_with model: [@organization, @event], local: true do |form| %>
      <%= errors_for @event %>
      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= form.hidden_field :creator_type, value: "Organization" %>
        <%= form.hidden_field :creator_id, value: path_segments[2] %>
        <%= form.hidden_field :creation_date, value: Time.current %>
      </div>
      <div class="form-group">
        <%= form.label :description %>
        <%= form.text_area :description, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= form.label :location %>
        <%= form.text_field :location, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= form.label :date %>
        <%= form.text_field :date, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= form.label :Make_private %>
        <%= form.check_box :privacy, {}, 1, 0 %>
      </div>
      <div class="form-group">
        <%= form.label :Event_image %>
        <%= form.file_field :image, class: "form-control-file" %>
      </div>
      <div class="form-group mt-2">
        <%= form.submit "Create", class: ["btn", "btn-primary"] %>
        <%= link_to "Back", user_events_path(current_user.id), class: ["btn", "btn-secondary"] %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/events/show.html.erb
<div class="row ml-0 mt-3">
  <ul class="list-unstyled">
    <% @event.each_with_index do |event| %>
      <h4 class="card-title"><%= event.name %>
        <% if user_signed_in? %>
          <% if event.creator_type == "User" %>
            <% if current_user.id == event.creator_id %>
              <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to "Edit", edit_event_path(event.id) %></button>
              <p class="float-right">
                <button type="button" class="btn btn-sm btn-outline-danger"><%= link_to "Delete", event, method: :delete, data: {confirm: "Are you sure?"}, remote: true%></button>
              </p>
            <% end %>
          <% elsif event.creator_type == "Organization" %>
            <% if OrganizationRole.where(user_id: current_user.id, organization_id: event.creator_id).pluck("role") == [1] %>
              <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to "Edit", edit_event_path(event.id) %></button>
              <p class="float-right">
                <button type="button" class="btn btn-sm btn-outline-danger"><%= link_to "Delete", event, method: :delete, data: {confirm: "Are you sure?"}, remote: true%></button>
              </p>
            <% end %>
          <% end %>
          <!-- button to assist public event
        <% if !@guests.pluck(:user_id).include? current_user.id & event.privacy == 0 %>
          <p class="float-right">
            <button type="button" class="btn btn-sm btn-outline-danger">
              <%= link_to "Assist", {:controller => 'invitations', :action => 'create', :user_id => current_user.id, :event_id => event, :host => '0'}, {:method => :post} %>
            </button>
          </p>
        <% end %>
        -->
        <% end %>

        <% if admin_signed_in? %>
          <p class="float-right">
            <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to "Edit", edit_event_path(event.id) %></button>
            <button type="button" class="btn btn-sm btn-outline-danger"><%= link_to "Delete", event, method: :delete, data: {confirm: "Are you sure?"}, remote: true%></button>
          </p>
        <% end %>
      </h4>
      <% if event.image.attached? == true%>
        <%= image_tag(event.image, width: "400px", background: "#55595c", color: "#eceeef") %>
      <% else %> <%= image_tag("thumbnail.svg", width: "400px", background: "#55595c", color: "#eceeef") %> <% end %>
    <% end %>
  </ul>
</div>

<div class="row ml-0 mt-3">
  <ul class="list-unstyled">
    <% @event.each_with_index do |event| %>
      <li><strong>Creation Date:</strong> <%= event.creation_date %></li>
      <% if event.creator_type == "User" %>
        <li><strong>Host:</strong> <%= link_to User.where(id: event.creator_id).pluck("username")[0], user_path(event.creator_id) %></li>
      <% else %>
        <li><strong>Host:</strong> <%= link_to Organization.where(id: event.creator_id).pluck("name")[0], organization_path(event.creator_id)%> </li>
      <% end %>
      <li><strong>Date:</strong> <%= event.date %></li>
      <li><strong>Location:</strong> <%= event.location %></li>
      <li><strong>Description:</strong> <%= event.description %></li>
    <% end %>
  </ul>
</div>

<div class="row ml-0 mt-3">
  <h4>Guest List</h4>
</div>
<% if user_signed_in? %>
  <div class="row ml-0 mt-3">
    <% if @event[0].creator_type == "User" %>
      <% if current_user.id == @event[0].creator_id %>
        <%= link_to 'Invite', new_event_invitation_path(@event[0].id), class: ["btn", "btn-primary"] %>
      <% end %>
    <% elsif @event[0].creator_type == "Organization" %>
      <% if OrganizationRole.where(user_id: current_user.id, organization_id: @event[0].creator_id).pluck("role") == [1] %>
        <%= link_to 'Invite', new_event_invitation_path(@event[0].id), class: ["btn", "btn-primary"] %>
      <% end %>
    <% end %>
  </div>
<% end %>
<div class="row ml-0 mt-3">
  <div class="row ml-0">
    <table class="table">
      <thead>
      <tr>
        <th scope="col">Username</th>
        <th scope="col">Name</th>
      </tr>
      </thead>
      <tbody>
      <% @guests.each_with_index do |guest| %>
        <tr>
          <td><%= link_to User.find(guest.user_id).username, user_path(guest.user_id) %></td>
          <td><%= User.find(guest.user_id).name %> <%= User.find(guest.user_id).lastName %></td>

          <% if user_signed_in? %>
            <% if @event[0].creator_type == "User" %>
              <% if current_user.id == @event[0].creator_id and guest.user_id != current_user.id  %>
                <td><button type="button" class="btn btn-sm btn-outline-danger"><%= link_to "Delete", guest, method: :delete, data: {confirm: "Are you sure?"}, remote: true%></button></td>
              <% end %>
            <% elsif @event[0].creator_type == "Organization" %>
              <% if OrganizationRole.where(user_id: current_user.id, organization_id: @event[0].creator_id).pluck("role") == [1] and guest.user_id != current_user.id %>
                <td><button type="button" class="btn btn-sm btn-outline-danger"><%= link_to "Delete", guest, method: :delete, data: {confirm: "Are you sure?"}, remote: true%></button></td>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>


<br>
<h4>Poll Section</h4>
<div class="card" style="width: 30rem;">
  <% if @votes_title.count == 0 %>

    <% if user_signed_in? %>
      <% if @event[0].creator_type == "User" %>
        <% if current_user.id == @event[0].creator_id %>
          <div class="row ml-0 ">
            <%= link_to "Create Poll", new_event_vote_path(@event[0].id) , class: ["btn", "btn-primary"] %>
          </div>
        <% end %>
      <% elsif @event[0].creator_type == "Organization" %>
        <% if OrganizationRole.where(user_id: current_user.id, organization_id: @event[0].creator_id).pluck("role") == [1] %>
          <div class="row ml-0 ">
            <%= link_to "Create Poll", new_event_vote_path(@event[0].id) , class: ["btn", "btn-primary"] %>
          </div>
        <% end %>
      <% end %>
    <% end %>

  <% else %>
    <h5 class="card-title"><% @votes_title.each_with_index do |votes_title| %>
        <tr>
          <h5><%= votes_title.options %></h5>
        </tr>
      <% end %>
    </h5>
    <div class="card-body">
      <strong>(1)</strong><span class="pull-right"> <%= @votes.where(vote: 1).count %></span><br>
      <strong>(2)</strong><span class="pull-right"> <%= @votes.where(vote: 2).count %></span>
      <br><br>
      <% if user_signed_in? %>
        <p>
          <% @guests.each_with_index do |guest| %>
            <% if guest.user_id == current_user.id %>
              <% if @votes.pluck("invitation_id").exclude? guest.id %>
                <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to "Vote", new_event_vote_path(@event[0].id) %></button>
              <% end %>
            <% end %>
          <% end %>
        </p>
      <% end %>
    </div>
  <% end %>
</div>

<br>

<div class="row ml-0 mt-3">
  <div class="panel panel-default widget">
    <div class="panel-heading">
      <span class="comment"></span>
      <h4 class="panel-title">Recent Comments</h4>
    </div>
    <% if user_signed_in? %>
      <% @guests.each_with_index do |guest| %>
        <% if guest.user_id == current_user.id %>
          <div class="row ml-0 mt-2 mb-3">
            <%= link_to "Add Comment", new_event_comment_path(@event[0].id) , class: ["btn", "btn-primary"] %>
          </div>
        <% end %>
      <% end %>
    <% end %>
    <div class="panel-body">
      <ul class="list-group">
        <% @comments.each_with_index do |comment| %>
          <tr>
            <li class="list-group-item">
              <div class="row">
                <div class="col-xs-10 col-md-12">
                  <div>
                    <%= link_to comment.username, user_path(comment.id) %>
                    <% if user_signed_in? %>
                      <% if comment.id == current_user.id %>
                        <p class="float-right">
                          <button type="button" class="btn btn-sm btn-outline-danger"><%= link_to "Edit", edit_comment_path(comment.comment_id) %></button>
                          <button type="button" class="btn btn-sm btn-outline-danger"><%= link_to "Delete", Comment.find(comment.comment_id), method: :delete, data: {confirm: "Are you sure?"}%></button>
                        </p>
                      <% elsif @event[0].creator_type == "User" %>
                        <% if current_user.id == @event[0].creator_id %>
                          <p class="float-right">
                            <button type="button" class="btn btn-sm btn-outline-danger"><%= link_to "Delete", Comment.find(comment.comment_id), method: :delete, data: {confirm: "Are you sure?"}%></button>
                          </p>
                        <% end %>
                      <% elsif @event[0].creator_type == "Organization" %>
                        <% if OrganizationRole.where(user_id: current_user.id, organization_id: @event[0].creator_id).pluck("role") == [1] %>
                          <p class="float-right">
                            <button type="button" class="btn btn-sm btn-outline-danger"><%= link_to "Delete", Comment.find(comment.comment_id), method: :delete, data: {confirm: "Are you sure?"}%></button>
                          </p>
                        <% end %>
                      <% end %>
                    <% end %>

                    <% if admin_signed_in? %>
                      <p class="float-right">
                        <button type="button" class="btn btn-sm btn-outline-danger"><%= link_to "Edit", edit_comment_path(comment.comment_id) %></button>
                        <button type="button" class="btn btn-sm btn-outline-danger"><%= link_to "Delete", Comment.find(comment.comment_id), method: :delete, data: {confirm: "Are you sure?"}%></button>
                      </p>
                    <% end %>
                  </div>
                  <div class="col-xs-10 col-md-12">
                    <%= comment.content %>
                  </div>
                </div>
              </div>
            </li>
          </tr>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<br>
<button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to 'Back', :back %></button>