config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: { sessions: 'admins/sessions' }
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home"

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :users, shallow: true do  #user has many events and has one org role
        resources :events, shallow: true
        resources :organization_roles, shallow: true
      end
      resources :organizations, shallow: true do  #orgs has many events and has many org roles
        resources :events, :organization_roles, shallow: true
      end
      resources :users, shallow: true do  #user has many invitations, which are linked to comments and votes
        resources :invitations, shallow: true do
          resources :comments, :votes, shallow: true
        end
      end
      resources :events, shallow: true do  #event has many invitations, comments and votes
        resources :invitations, :comments, :votes, shallow: true
      end
    end
  end

  resources :users, defaults: { format: :html }, shallow: true do  #user has many events, messages and has one org role
    resources :messages, defaults: { format: :html }, shallow: true
    resources :events, defaults: { format: :html }, shallow: true do
      resources :invitations, :comments, :votes, defaults: { format: :html }, shallow: true
    end
    resources :organization_roles, defaults: { format: :html }, shallow: true
  end
  resources :organizations, defaults: { format: :html }, shallow: true do  #orgs has many events and has many org roles
    resources :events, defaults: { format: :html }, shallow: true do
      resources :invitations, :comments, :votes, defaults: { format: :html }, shallow: true
    end
    resources :organization_roles, defaults: { format: :html }, shallow: true
  end
  resources :users, defaults: { format: :html }, shallow: true do  #user has many invitations, which are linked to comments and votes
    resources :invitations, defaults: { format: :html }, shallow: true do
      resources :comments, :votes, defaults: { format: :html }, shallow: true
    end
  end

  resource :aup_tos, only: [:show]
  match '/search_users', to: "search_users#search_users", via: [:post, :get]
  match '/search_organizations', to: "search_organizations#search_organizations", via: [:post, :get]
  match '/search_events', to: "search_events#search_events", via: [:post, :get]

end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :organization_roles, dependent: :destroy
  has_many :users, through: :organization_roles
  has_many :events, as: :creator, dependent: :destroy

  has_one_attached :org_image

  validates :name, :description, presence: true
  validates :name, uniqueness: true
end

app/controllers/api/v1/organizations_controller.rb
class API::V1::OrganizationsController < APIController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)

    if @organization.save
      render :show, status: :created, location: @organization
    else
      render json: @organization.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    if @organization.update(organization_params)
      render :show, status: :ok, location: api_v1_organizations_path(@organization)
    else
      render json: @organization.errors, status: :unprocessable_entity
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    head :no_content
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def organization_params
      params.fetch(:organization, {}).permit(:id, :name)
    end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
    @organization = Organization.where(id: params[:id])
    @admin = OrganizationRole.includes(:user, :organization).where(organization_id: params[:id], role: 1)[0]
    @members = OrganizationRole.includes(:user, :organization).where(organization_id: params[:id])

    @events = Event.where(creator_id: params[:id], creator_type: "Organization", privacy: 0)
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        @new_organization_admin = OrganizationRole.new
        @new_organization_admin.user = current_user
        @new_organization_admin.organization = @organization
        @new_organization_admin.role = 1
        if @new_organization_admin.errors.blank?
          @new_organization_admin.save
        end

        format.html { redirect_to organizations_path, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def organization_params
      params.fetch(:organization, {}).permit(:id, :name, :description, :org_image, :user_id, :organization_id,
                                             organization_roles_attributes: [:id, :user, :organization, :role, :_destroy])
    end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<div class="row ml-0">
  <%= form_with model: @organization, local: true do |form| %>
    <%= errors_for @organization %>
    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :description %>
      <%= form.text_area :description, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :Organization_image %>
      <%= form.file_field :org_image, class: "form-control-file" %>
    </div>

    <%=form.fields_for :organization_roles do |organization_role_form| %>
      <div class="form-group">
        <%= organization_role_form.hidden_field :role, value: 1 %>
      </div>
    <% end %>

    <div class="form-group mt-2">
      <%= form.submit submit_btn_text, class: ["btn", "btn-primary"] %>
      <%= link_to "Back", organizations_path, class: ["btn", "btn-secondary"] %>
    </div>
  <% end %>
</div>

app/views/organizations/edit.html.erb
<div class="row ml-0 mt-3">
  <h2>Edit "<%=@organization.name%>" Profile</h2>
</div>
<div class="row ml-0 mt-2">
  <p>Please enter the required information to edit "<%=@organization.name%>" profile:</p>
</div>
<%= render partial: "form",
           locals: {
               organization: @organization,
               submit_btn_text: "Update"
           } %>

app/views/organizations/index.html.erb
<div class="row ml-0 mt-3">
  <h4>Organizations</h4>
</div>

<% if user_signed_in? %>
  <div class="row ml-0 mt-2 mb-3">
    <%= link_to 'New Organization', new_organization_path, class: ["btn", "btn-primary"] %>
  </div>
<% end %>

<form class="form-inline mr-3" id="search_form">
  <input class="form-control mr-sm-2" id="search_box" type="search" placeholder="Search" aria-label="Search">
  <button class="btn btn-outline-success my-2 my-sm-0" id="search_organizations_button" type="submit">Search</button>
</form>

<div class="row ml-0 mt-3">
  <% if @organizations.count == 0 %>
    <div class="row ml-0">
      No organizations at the moment!
    </div>
  <% else %>
    <% @organizations.each_with_index do |organization| %>
      <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
          <div class="card-body">
            <p class="card-text"><%= link_to organization.name, organization %></p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to "View", organization %></button>
                <% if user_signed_in? %>
                  <% if OrganizationRole.where(user_id: current_user.id, organization_id: organization.id).pluck("role") == [1]%>
                    <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to "Edit", edit_organization_path(organization) %></button>
                    <button type="button" class="btn btn-sm btn-outline-danger"><%= link_to "Delete", organization, method: :delete, data: {confirm: "Are you sure?"}, remote: true%></button>
                  <% end %>
                <% end %>
                <% if admin_signed_in? %>
                  <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to "Edit", edit_organization_path(organization) %></button>
                  <button type="button" class="btn btn-sm btn-outline-danger"><%= link_to "Delete", organization, method: :delete, data: {confirm: "Are you sure?"}, remote: true%></button>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

<div class="row ml-0 mt-3">
  <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to 'Back', root_path %></button>
</div>

app/views/organizations/new.html.erb
<div class="row ml-0 mt-3">
  <h4>New Organization</h4>
</div>
<div class="row ml-0 mt-2">
  <p>Please enter the required information to create a new Organization:</p>
</div>
<%= render partial: "form",
           locals: {
               organization: @organization,
               submit_btn_text: "Create"
           } %>

app/views/organizations/show.html.erb
<div class="row ml-0 mt-3">
  <ul class="list-unstyled">
    <% @organization.each_with_index do |organization| %>
      <h4 class="card-title"><%= organization.name %>
        <% if user_signed_in? %>
          <% if OrganizationRole.where(user_id: current_user.id, organization_id: organization).pluck("role") == [1] %>
            <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to "Edit", edit_organization_path(organization.id) %></button>
            <p class="float-right">
              <button type="button" class="btn btn-sm btn-outline-danger"><%= link_to "Delete", organization, method: :delete, data: {confirm: "Are you sure?"}, remote: true%></button>
            </p>
          <% elsif OrganizationRole.where(user_id: current_user.id, organization_id: organization).count == 0 %>
            <p class="float-right">
              <%= link_to "Join", new_organization_organization_role_path(@organization[0].id), class: ["btn", "btn-sm btn-outline-secondary"] %>
            </p>
          <% end %>
        <% end %>
        <% if admin_signed_in? %>
          <p class="float-right">
            <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to "Edit", edit_organization_path(organization.id) %></button>
            <button type="button" class="btn btn-sm btn-outline-danger"><%= link_to "Delete", organization, method: :delete, data: {confirm: "Are you sure?"}, remote: true%></button>
          </p>
        <% end %>
      </h4>
      <% if organization.org_image.attached? == true%>
        <%= image_tag(organization.org_image, width: "400px", background: "#55595c", color: "#eceeef") %>
      <% else %> <%= image_tag("thumbnail.svg", width: "400px", background: "#55595c", color: "#eceeef") %> <% end %>
    <% end %>
  </ul>
</div>
<div class="row ml-0 mt-3">
  <ul class="list-unstyled">
    <% @organization.each_with_index do |organization| %>
        <li><strong>Moderator:</strong> <%= link_to @admin.user.username , user_path(@admin.user.id) %></li>
        <li><strong>Description:</strong> <%= organization.description %></li>
        <% end %>
  </ul>
</div>

<div class="row ml-0 mt-3">
  <h5>Public Events</h5>
</div>
<div class="row ml-0">
  <ul class="list-unstyled">
    <% if @events.count == 0 %>
      <div class="row ml-0 ">
        No public events at the moment!
      </div>
    <% else %>
      <% @events.each_with_index do |event| %>
        <li><strong><%= link_to event.name, event_path(event.id) %></strong></li>
      <% end %>
    <% end %>
  </ul>
</div>

<div class="row ml-0 mt-3">
  <h5>Members</h5>
</div>
<div class="row ml-0">
  <table class="table">
    <thead>
    <tr>
      <th scope="col">Username</th>
      <th scope="col">Role</th>
      <% if user_signed_in? %>
        <th scope="col">Action</th>
      <% end %>
    </tr>
    </thead>
    <tbody>
    <% @members.each_with_index do |member| %>
      <tr>
        <td><%= link_to member.user.username, user_path(member.user.id) %></td>
        <td><% if member.role == 0 %> Normal <% else %> Moderator <% end %></td>
        <% if user_signed_in? %>
          <% if current_user.id == @admin.user.id and member.user.id != current_user.id %>
            <td><button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to "Remove", member, method: :delete, data: {confirm: "Are you sure?"}, remote: true%></button></td>
          <% elsif current_user.id != @admin.user.id and member.user.id == current_user.id %>
            <td><button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to "Leave", member, method: :delete, data: {confirm: "Are you sure?"}, remote: true%></button></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<div class="row ml-0 mt-3">
  <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to 'Back', :back %></button>
</div>